# -*- coding: utf-8 -*-
# scout_engine.py - Base de Datos Global MAIA FKT

def get_market_scout():
    return [
        # --- AMÉRICA ---
        {"id": "SC-USA-01", "Nombre": "Solar Texas Hub", "Ubicación": "USA", "Valor_Est": "USD 210M", "Potencia": "400 MW", "Riesgo": "MÍNIMO", "Calificacion_IA": "9.8/10", "Tipo": "Eléctrico", "Resumen": "Granja solar con almacenamiento Tesla Megapack.", "CEO": "Elon Musk (Ref)", "Celular": "+1 512 555 0199", "Dirección": "1 Tesla Road, Austin, TX", "Contacto": "m&a@texashub.com", "Vigencia": "10-ENE-2027", "Fuente": "DOE", "Viabilidad": 98},
        {"id": "SC-CAN-01", "Nombre": "Ontario Wind Farm", "Ubicación": "Canadá", "Valor_Est": "USD 150M", "Potencia": "200 MW", "Riesgo": "BAJO", "Calificacion_IA": "9.2/10", "Tipo": "Eléctrico", "Resumen": "Parque eólico onshore con turbinas de última generación.", "CEO": "Justin Trudeau (Gov)", "Celular": "+1 416 999 0233", "Dirección": "Bay St, Toronto, ON", "Contacto": "energy@ontario.ca", "Vigencia": "15-MAR-2027", "Fuente": "NRCan", "Viabilidad": 92},
        {"id": "SC-MEX-01", "Nombre": "Solar Sonora", "Ubicación": "México", "Valor_Est": "USD 300M", "Potencia": "1 GW", "Riesgo": "MEDIO", "Calificacion_IA": "8.5/10", "Tipo": "Eléctrico", "Resumen": "Megaproyecto fotovoltaico estatal.", "CEO": "Manuel Bartlett (CFE)", "Celular": "+52 55 1234 5678", "Dirección": "Av. Reforma 164, CDMX", "Contacto": "licitaciones@cfe.mx", "Vigencia": "20-JUN-2027", "Fuente": "SENER", "Viabilidad": 85},
        {"id": "SC-COL-01", "Nombre": "Eólico La Guajira", "Ubicación": "Colombia", "Valor_Est": "USD 45M", "Potencia": "120 MW", "Riesgo": "BAJO", "Calificacion_IA": "9.5/10", "Tipo": "Eléctrico", "Resumen": "Expansión de red en zona norte.", "CEO": "Ricardo Roa (Ecopetrol)", "Celular": "+57 310 456 7890", "Dirección": "Cra 13 #36-24, Bogotá", "Contacto": "proyectos@upme.co", "Vigencia": "31-DIC-2026", "Fuente": "UPME", "Viabilidad": 92},
        {"id": "SC-BRA-01", "Nombre": "Amazonas Hydro", "Ubicación": "Brasil", "Valor_Est": "USD 180M", "Potencia": "300 MW", "Riesgo": "MEDIO", "Calificacion_IA": "8.2/10", "Tipo": "Eléctrico", "Resumen": "Hidroeléctrica de bajo impacto ambiental.", "CEO": "Wilson Ferreira Jr", "Celular": "+55 21 98877 6655", "Dirección": "Rua da Quitanda, RJ", "Contacto": "invest@aneel.gov.br", "Vigencia": "15-MAR-2027", "Fuente": "ANEEL", "Viabilidad": 75},
        {"id": "SC-ARG-01", "Nombre": "Litio Salta", "Ubicación": "Argentina", "Valor_Est": "USD 50M", "Potencia": "N/A", "Riesgo": "ALTO", "Calificacion_IA": "7.9/10", "Tipo": "Minería/Baterías", "Resumen": "Extracción de litio en el Triángulo del Litio.", "CEO": "Daniel González (YPF)", "Celular": "+54 11 4321 0000", "Dirección": "Macacha Güemes 515, CABA", "Contacto": "mining@ypf.com.ar", "Vigencia": "05-SEP-2026", "Fuente": "Secretaría Minería", "Viabilidad": 70},
        {"id": "SC-PER-01", "Nombre": "Solar Moquegua", "Ubicación": "Perú", "Valor_Est": "USD 85M", "Potencia": "140 MW", "Riesgo": "BAJO", "Calificacion_IA": "9.0/10", "Tipo": "Eléctrico", "Resumen": "Planta fotovoltaica en el sur del Perú.", "CEO": "Victor Gobitz", "Celular": "+51 1 611 0000", "Dirección": "San Borja, Lima", "Contacto": "minem@gob.pe", "Vigencia": "22-OCT-2026", "Fuente": "MINEM", "Viabilidad": 90},
        
        # --- EUROPA ---
        {"id": "SC-GER-01", "Nombre": "Báltico Wind", "Ubicación": "Alemania", "Valor_Est": "USD 500M", "Potencia": "1 GW", "Riesgo": "BAJO", "Calificacion_IA": "9.0/10", "Tipo": "Eléctrico", "Resumen": "Eólico marino profundo.", "CEO": "Christian Bruch (Siemens)", "Celular": "+49 89 2340", "Dirección": "Wittelsbacherplatz 2, Munich", "Contacto": "energy@bundes.de", "Vigencia": "20-JUN-2027", "Fuente": "BMWK", "Viabilidad": 90},
        {"id": "SC-SPA-01", "Nombre": "Sevilla Sun", "Ubicación": "España", "Valor_Est": "USD 95M", "Potencia": "150 MW", "Riesgo": "MÍNIMO", "Calificacion_IA": "9.3/10", "Tipo": "Eléctrico", "Resumen": "Planta operativa con PPA.", "CEO": "Ignacio Galán (Iberdrola)", "Celular": "+34 91 784 2200", "Dirección": "Tomás Redondo 1, Madrid", "Contacto": "ops@ree.es", "Vigencia": "30-SEP-2026", "Fuente": "IDAE", "Viabilidad": 94},
        {"id": "SC-FRA-01", "Nombre": "H2 Nantes", "Ubicación": "Francia", "Valor_Est": "USD 250M", "Potencia": "300 MW", "Riesgo": "MEDIO", "Calificacion_IA": "8.8/10", "Tipo": "Hidrógeno", "Resumen": "Hub de hidrógeno verde portuario.", "CEO": "Luc Rémont (EDF)", "Celular": "+33 1 40 42 22 22", "Dirección": "Avenue de Wagram, Paris", "Contacto": "h2@edf.fr", "Vigencia": "12-DIC-2026", "Fuente": "ADEME", "Viabilidad": 88},
        {"id": "SC-ITA-01", "Nombre": "Sicilia Agri-Voltaic", "Ubicación": "Italia", "Valor_Est": "USD 120M", "Potencia": "200 MW", "Riesgo": "BAJO", "Calificacion_IA": "9.1/10", "Tipo": "Eléctrico", "Resumen": "Uso dual de suelo: Agrícola y Solar.", "CEO": "Francesco Starace (Enel)", "Celular": "+39 06 83051", "Dirección": "Viale Regina Margherita, Roma", "Contacto": "projects@enel.it", "Vigencia": "18-MAY-2027", "Fuente": "GSE", "Viabilidad": 91},
        {"id": "SC-UK-01", "Nombre": "Dogger Bank Expansion", "Ubicación": "Reino Unido", "Valor_Est": "USD 400M", "Potencia": "800 MW", "Riesgo": "MÍNIMO", "Calificacion_IA": "9.7/10", "Tipo": "Eléctrico", "Resumen": "Expansión del mayor parque eólico marino.", "CEO": "Alistair Phillips-Davies", "Celular": "+44 1738 456000", "Dirección": "Inveralmond House, Perth", "Contacto": "invest@sse.com", "Vigencia": "01-ENE-2028", "Fuente": "Ofgem", "Viabilidad": 97},
        
        # --- ASIA / ORIENTE (Mantenidos) ---
        {"id": "SC-CHN-01", "Nombre": "Shanghai Grid", "Ubicación": "China", "Valor_Est": "USD 1.2B", "Potencia": "5 GW", "Riesgo": "MEDIO", "Calificacion_IA": "7.5/10", "Tipo": "Red Intel", "CEO": "Xin Baoan", "Celular": "+86 10 6659 8114", "Dirección": "Xicheng District, Beijing", "Contacto": "grid@stategrid.cn", "Vigencia": "01-DIC-2027", "Fuente": "NEA", "Viabilidad": 70},
        {"id": "SC-SAU-01", "Nombre": "Neom H2 Plant", "Ubicación": "Los Árabes", "Valor_Est": "USD 900M", "Potencia": "2 GW", "Riesgo": "MEDIO", "Calificacion_IA": "8.9/10", "Tipo": "H2 Verde", "CEO": "Nadhmi Al-Nasr", "Celular": "+966 11 800 0000", "Dirección": "NEOM HQ, Tabuk", "Contacto": "m&a@neom.sa", "Vigencia": "01-FEB-2028", "Fuente": "PIF", "Viabilidad": 85}
    ]