# -*- coding: utf-8 -*-
# scout_engine.py - Motor de Inteligencia MAIA FKT: Energía y Deep Tech

def get_market_scout():
    return [
        # --- AMÉRICA (SMR & STARTUPS) ---
        {"id": "SC-USA-02", "Nombre": "NuScale SMR Hub", "Ubicación": "América (USA)", "Valor_Est": "USD 1.5B", "Tecnología": "SMR Nuclear", "Riesgo": "ALTO", "Calificacion_IA": "9.4/10", "Resumen": "Primer despliegue comercial de reactores modulares pequeños. Tecnología aprobada por NRC.", "CEO": "John Hopkins", "Celular": "+1 503 350 3900", "Dirección": "6650 SW Redwood Lane, Portland", "Contacto": "ir@nuscalepower.com", "Vigencia": "12-DIC-2028", "Fuente": "NRC USA", "Viabilidad": 82},
        {"id": "SC-CAN-02", "Nombre": "DeepTech Neutrino Lab", "Ubicación": "América (Canadá)", "Valor_Est": "USD 80M", "Tecnología": "Neutrinos / Sensores", "Riesgo": "CRÍTICO", "Calificacion_IA": "8.1/10", "Resumen": "Startup enfocada en detección de neutrinos para comunicaciones seguras subacuáticas.", "CEO": "Arthur McDonald (Consultant)", "Celular": "+1 613 533 2702", "Dirección": "Kingston, Ontario", "Contacto": "research@snolab.ca", "Vigencia": "01-ENE-2027", "Fuente": "SNO+", "Viabilidad": 65},
        
        # --- EUROPA (HIDRÓGENO & SMR) ---
        {"id": "SC-UK-02", "Nombre": "Rolls-Royce SMR Program", "Ubicación": "Europa (UK)", "Valor_Est": "USD 2.1B", "Tecnología": "SMR Nuclear", "Riesgo": "MODERADO", "Calificacion_IA": "9.6/10", "Resumen": "Diseño de reactores compactos para descarbonización industrial masiva.", "CEO": "Tufan Erginbilgic", "Celular": "+44 20 7222 9020", "Dirección": "Kings Place, London", "Contacto": "smr@rolls-royce.com", "Vigencia": "20-MAY-2030", "Fuente": "UK Gov", "Viabilidad": 89},
        {"id": "SC-SPA-02", "Nombre": "H2 Med Pipeline", "Ubicación": "Europa (España)", "Valor_Est": "USD 2.5B", "Tecnología": "Hidrógeno Verde", "Riesgo": "MODERADO", "Calificacion_IA": "9.1/10", "Resumen": "Corredor de hidrógeno verde conectando Barcelona con Marsella.", "CEO": "Arturo Gonzalo (Enagás)", "Celular": "+34 91 709 9200", "Dirección": "Paseo de los Olmos, Madrid", "Contacto": "proyectos@enagas.es", "Vigencia": "31-DIC-2029", "Fuente": "UE / IPCEI", "Viabilidad": 85},
        {"id": "SC-FRA-02", "Nombre": "Startup Neutrino-Energy", "Ubicación": "Europa (Francia)", "Valor_Est": "USD 12M", "Tecnología": "Neutrinovoltaica", "Riesgo": "MUY ALTO", "Calificacion_IA": "7.5/10", "Resumen": "Captación de energía de neutrinos y otras radiaciones invisibles. Fase pre-semilla.", "CEO": "Holger Thorsten Schubart", "Celular": "+33 1 84 88 06 44", "Dirección": "Avenue George V, Paris", "Contacto": "office@neutrino-energy.com", "Vigencia": "15-OCT-2026", "Fuente": "Neutrino Group", "Viabilidad": 40},

        # --- ASIA / ORIENTE (STARTUPS & H2) ---
        {"id": "SC-JPN-02", "Nombre": "Toyota H2 Port", "Ubicación": "Japón", "Valor_Est": "USD 600M", "Tecnología": "Hidrógeno Verde", "Riesgo": "BAJO", "Calificacion_IA": "9.7/10", "Resumen": "Logística portuaria basada 100% en celdas de combustible de hidrógeno.", "CEO": "Koji Sato", "Celular": "+81 565 28 2121", "Dirección": "Toyota City, Aichi", "Contacto": "global-pr@toyota.jp", "Vigencia": "01-JUL-2027", "Fuente": "METI", "Viabilidad": 95}
    ]