# -*- coding: utf-8 -*-
# scout_engine.py - REPOSITORIO COMPLETO DE INTELIGENCIA MAIA FKT

def get_market_scout():
    return [
        # --- AMÉRICA: DEEP TECH, SMR & RENEWABLES ---
        {"id": "SC-USA-01", "Nombre": "Solar Texas Hub", "Ubicación": "América (USA)", "Valor_Est": "USD 210M", "Tecnología": "Solar + Baterías", "Riesgo": "MÍNIMO", "Calificacion_IA": "9.8/10", "Resumen": "Granja solar masiva con almacenamiento Tesla Megapack para estabilidad de red.", "CEO": "Elon Musk (Ref)", "Celular": "+1 512 555 0199", "Dirección": "1 Tesla Road, Austin, TX", "Contacto": "m&a@texashub.com", "Vigencia": "10-ENE-2027", "Fuente": "DOE USA", "Viabilidad": 98},
        {"id": "SC-USA-02", "Nombre": "NuScale SMR Hub", "Ubicación": "América (USA)", "Valor_Est": "USD 1.5B", "Tecnología": "SMR Nuclear", "Riesgo": "ALTO", "Calificacion_IA": "9.4/10", "Resumen": "Despliegue de reactores modulares pequeños. Primera certificación NRC para diseño modular.", "CEO": "John Hopkins", "Celular": "+1 503 350 3900", "Dirección": "6650 SW Redwood Lane, Portland", "Contacto": "ir@nuscalepower.com", "Vigencia": "12-DIC-2028", "Fuente": "NRC / DOE", "Viabilidad": 82},
        {"id": "SC-CAN-01", "Nombre": "Ontario Wind Farm", "Ubicación": "América (Canadá)", "Valor_Est": "USD 150M", "Tecnología": "Eólico Onshore", "Riesgo": "BAJO", "Calificacion_IA": "9.2/10", "Resumen": "Parque eólico con integración de IA para predicción de despacho.", "CEO": "Justin Trudeau (Gov Ref)", "Celular": "+1 416 999 0233", "Dirección": "Bay St, Toronto, ON", "Contacto": "energy@ontario.ca", "Vigencia": "15-MAR-2027", "Fuente": "NRCan", "Viabilidad": 92},
        {"id": "SC-CAN-02", "Nombre": "DeepTech Neutrino Lab", "Ubicación": "América (Canadá)", "Valor_Est": "USD 80M", "Tecnología": "Neutrinos", "Riesgo": "CRÍTICO", "Calificacion_IA": "8.1/10", "Resumen": "Startup de sensores de neutrinos para comunicaciones encriptadas de alta profundidad.", "CEO": "Arthur McDonald (Consultant)", "Celular": "+1 613 533 2702", "Dirección": "Kingston, Ontario", "Contacto": "research@snolab.ca", "Vigencia": "01-ENE-2027", "Fuente": "SNO+ / Queens Univ", "Viabilidad": 65},
        {"id": "SC-MEX-01", "Nombre": "Solar Sonora", "Ubicación": "América (México)", "Valor_Est": "USD 300M", "Tecnología": "Fotovoltaica", "Riesgo": "MEDIO", "Calificacion_IA": "8.5/10", "Resumen": "Megaproyecto estatal de generación fotovoltaica en el desierto de Sonora.", "CEO": "Manuel Bartlett (CFE)", "Celular": "+52 55 1234 5678", "Dirección": "Av. Reforma 164, CDMX", "Contacto": "licitaciones@cfe.mx", "Vigencia": "20-JUN-2027", "Fuente": "SENER", "Viabilidad": 85},
        {"id": "SC-COL-01", "Nombre": "Eólico La Guajira", "Ubicación": "América (Colombia)", "Valor_Est": "USD 45M", "Tecnología": "Eólico Onshore", "Riesgo": "BAJO", "Calificacion_IA": "9.5/10", "Resumen": "Licitación para expansión de red. Alta radiación eólica constante.", "CEO": "Ricardo Roa (Ecopetrol)", "Celular": "+57 310 456 7890", "Dirección": "Cra 13 #36-24, Bogotá", "Contacto": "proyectos@upme.co", "Vigencia": "31-DIC-2026", "Fuente": "UPME", "Viabilidad": 92},
        {"id": "SC-BRA-01", "Nombre": "Amazonas Hydro", "Ubicación": "América (Brasil)", "Valor_Est": "USD 180M", "Tecnología": "Hidroeléctrica", "Riesgo": "MEDIO", "Calificacion_IA": "8.2/10", "Resumen": "Hidroeléctrica de pasada con tecnología de turbinas de bajo impacto.", "CEO": "Wilson Ferreira Jr", "Celular": "+55 21 98877 6655", "Dirección": "Rua da Quitanda, RJ", "Contacto": "invest@aneel.gov.br", "Vigencia": "15-MAR-2027", "Fuente": "ANEEL", "Viabilidad": 75},
        {"id": "SC-ARG-01", "Nombre": "Litio Salta", "Ubicación": "América (Argentina)", "Valor_Est": "USD 50M", "Tecnología": "Minería / Litio", "Riesgo": "ALTO", "Calificacion_IA": "7.9/10", "Resumen": "Extracción y procesamiento de carbonato de litio grado batería.", "CEO": "Daniel González (YPF)", "Celular": "+54 11 4321 0000", "Dirección": "Macacha Güemes 515, CABA", "Contacto": "mining@ypf.com.ar", "Vigencia": "05-SEP-2026", "Fuente": "Secretaría Minería", "Viabilidad": 70},
        {"id": "SC-PER-01", "Nombre": "Solar Moquegua", "Ubicación": "América (Perú)", "Valor_Est": "USD 85M", "Tecnología": "Fotovoltaica", "Riesgo": "BAJO", "Calificacion_IA": "9.0/10", "Resumen": "Planta fotovoltaica de alta eficiencia en zona de alta radiación desértica.", "CEO": "Victor Gobitz", "Celular": "+51 1 611 0000", "Dirección": "San Borja, Lima", "Contacto": "minem@gob.pe", "Vigencia": "22-OCT-2026", "Fuente": "MINEM", "Viabilidad": 90},

        # --- EUROPA: H2, NUCLEAR & NEUTRINOS ---
        {"id": "SC-GER-01", "Nombre": "Báltico Wind", "Ubicación": "Europa (Alemania)", "Valor_Est": "USD 500M", "Tecnología": "Eólico Offshore", "Riesgo": "BAJO", "Calificacion_IA": "9.0/10", "Resumen": "Parque eólico marino profundo. Uso de turbinas Siemens Gamesa.", "CEO": "Christian Bruch", "Celular": "+49 89 2340", "Dirección": "Wittelsbacherplatz 2, Munich", "Contacto": "energy@bundes.de", "Vigencia": "20-JUN-2027", "Fuente": "BMWK", "Viabilidad": 90},
        {"id": "SC-UK-02", "Nombre": "Rolls-Royce SMR", "Ubicación": "Europa (UK)", "Valor_Est": "USD 2.1B", "Tecnología": "SMR Nuclear", "Riesgo": "MODERADO", "Calificacion_IA": "9.6/10", "Resumen": "Desarrollo de reactores modulares para redes industriales cerradas.", "CEO": "Tufan Erginbilgic", "Celular": "+44 20 7222 9020", "Dirección": "Kings Place, London", "Contacto": "smr@rolls-royce.com", "Vigencia": "20-MAY-2030", "Fuente": "UK Gov", "Viabilidad": 89},
        {"id": "SC-SPA-02", "Nombre": "H2 Med Corredor", "Ubicación": "Europa (España)", "Valor_Est": "USD 2.5B", "Tecnología": "Hidrógeno Verde", "Riesgo": "MODERADO", "Calificacion_IA": "9.1/10", "Resumen": "Primer corredor de hidrógeno verde entre la Península y Francia.", "CEO": "Arturo Gonzalo", "Celular": "+34 91 709 9200", "Dirección": "Paseo de los Olmos, Madrid", "Contacto": "proyectos@enagas.es", "Vigencia": "31-DIC-2029", "Fuente": "IPCEI / Enagás", "Viabilidad": 85},
        {"id": "SC-FRA-02", "Nombre": "Neutrino Energy FR", "Ubicación": "Europa (Francia)", "Valor_Est": "USD 12M", "Tecnología": "Neutrinovoltaica", "Riesgo": "MUY ALTO", "Calificacion_IA": "7.5/10", "Resumen": "Startup enfocada en la recolección de energía térmica de neutrinos.", "CEO": "Holger Schubart", "Celular": "+33 1 84 88 06 44", "Dirección": "Avenue George V, Paris", "Contacto": "office@neutrino-energy.com", "Vigencia": "15-OCT-2026", "Fuente": "Neutrino Group", "Viabilidad": 40},
        {"id": "SC-ITA-01", "Nombre": "Sicilia Agri-Voltaic", "Ubicación": "Europa (Italia)", "Valor_Est": "USD 120M", "Tecnología": "Agro-Voltaica", "Riesgo": "BAJO", "Calificacion_IA": "9.1/10", "Resumen": "Integración de paneles solares en cultivos de vid para optimización de suelo.", "CEO": "Francesco Starace", "Celular": "+39 06 83051", "Dirección": "Viale Regina Margherita, Roma", "Contacto": "projects@enel.it", "Vigencia": "18-MAY-2027", "Fuente": "GSE / Enel", "Viabilidad": 91},

        # --- ASIA / ORIENTE ---
        {"id": "SC-SAU-01", "Nombre": "Neom H2 Plant", "Ubicación": "Los Árabes (KSA)", "Valor_Est": "USD 900M", "Tecnología": "Hidrógeno Verde", "Riesgo": "MEDIO", "Calificacion_IA": "8.9/10", "Resumen": "Producción masiva de H2 para exportación global usando energía solar.", "CEO": "Nadhmi Al-Nasr", "Celular": "+966 11 800 0000", "Dirección": "NEOM HQ, Tabuk", "Contacto": "m&a@neom.sa", "Vigencia": "01-FEB-2028", "Fuente": "PIF Saudi", "Viabilidad": 85},
        {"id": "SC-JPN-02", "Nombre": "Toyota H2 Port", "Ubicación": "Asia (Japón)", "Valor_Est": "USD 600M", "Tecnología": "Hidrógeno Verde", "Riesgo": "BAJO", "Calificacion_IA": "9.7/10", "Resumen": "Ecosistema de transporte portuario basado en celdas de combustible H2.", "CEO": "Koji Sato", "Celular": "+81 565 28 2121", "Dirección": "Toyota City, Aichi", "Contacto": "global-pr@toyota.jp", "Vigencia": "01-JUL-2027", "Fuente": "METI", "Viabilidad": 95}
    ]